LP Hud fix
GTNewHorizons/BloodMagic pull request #59
Opened 2024-10-06 13:45 UTC by Fabboz

fix lp hud with waila and botania when targeting a block like grass and with mana bar present.
I took the hud code of the Thaumcraft sanity checker as a reference.

this is the bug before the commit:
![Senzanome](https://github.com/user-attachments/assets/3938d804-4443-4f94-8c4a-2e7d2525de6a)

after: fixed!

2024-10-06 19:40 UTC, OneEyeMaker commented on src/main/java/WayofTime/alchemicalWizardry/client/renderer/RenderHelper.java
> +		GL11.glEnable(3042);
Please, use constants defined in `GL11` class for better readability:
```suggestion
		GL11.glEnable(GL11.GL_BLEND);
```
For blending you should also specify function via `GL11.glBleendFunc`.

2024-10-06 19:43 UTC, OneEyeMaker commented on src/main/java/WayofTime/alchemicalWizardry/client/renderer/RenderHelper.java
> +		GL11.glEnable(3042);
Also, run `./gradlew spotlessApply` when you're done to fix formatting.

2024-10-06 21:16 UTC, Fabboz commented
i can't do better than that

2024-10-06 21:18 UTC, Alastors requested changes
Legally we can't allow this, it's a great way for us to get cease and desisted

2024-10-06 21:29 UTC, Fabboz commented
i'm not a programmer. I would be happy if someone made these changes for me. Thank you

2024-10-06 21:54 UTC, Fabboz commented
And i found that is automagy that made that bug with botania and bloodmagic  and waila

2024-10-19 11:37 UTC, Fabboz commented
i'm sorry i don't know how to run spotlessapply in my workspace sorry

2024-10-19 11:40 UTC, lordIcocain commented
./gradlew build spotlessApply
in terminal

2024-10-19 19:06 UTC, Dream-Master commented
@Fabboz wh you close this ?

2024-10-19 21:44 UTC, Fabboz commented
> @Fabboz wh you close this ?

I cant make the changes requested

2024-10-20 09:36 UTC, Dream-Master commented
@Fabboz i did it for you
update dependencies as well

2024-10-20 09:39 UTC, chochem commented
if they used ARR code then we cant use this, Dream

2024-10-20 09:40 UTC, Dream-Master commented
@chochem ARR code ? its just some render code changes? Or i am wrong ?

2024-10-20 09:41 UTC, chochem commented
which they say they took from thaumcraft

2024-10-20 09:45 UTC, Dream-Master commented
> which they say they took from thaumcraft

even if people can use code fragments to improve other code? I don't see a problem here. Should I call a lawyer? :trollface:

2024-10-20 10:00 UTC, Fabboz commented
> @Fabboz i did it for you update dependencies as well

thx.

it's not a copy paste.

2024-10-20 10:04 UTC, boubou19 commented
Nothing thaumcraft related in there, it's base OGL manipulation.

2024-10-20 10:08 UTC, chochem commented
they literally say so in the description boubou

2024-10-20 10:08 UTC, boubou19 approved these changes

2024-10-20 10:08 UTC, merged